workspace:
  base: /root/go-projects/
  path: src/git.ultraware.nl/NiseVoid/qb

pipeline:
  test:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    commands:
      - make setup
      - go get git.ultraware.nl/NiseVoid/funlen
      - make test
      - make lint
      - go test -bench=.
    when:
      event: [ push, tag, pull_request ]

  PostgreSQL:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    environment:
      - POSTGRES_TESTHOST=pgsql
    commands:
      - make setup
      - make test_postgres
    when:
      event: [ push, tag, pull_request ]

  MySQL:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    environment:
      - MYSQL_TESTHOST=mariadb
    commands:
      - make setup
      - make test_mysql
    when:
      event: [ push, tag, pull_request ]

  MSSQL:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    environment:
      - MSSQL_TESTHOST=172.22.0.25
    commands:
      - make setup
      - make test_mssql
    when:
      event: [ push, tag, pull_request ]

services:
  pgsql:
    image: postgres:10.1-alpine
    pull: true
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=qb_test
      - POSTGRES_DB=qb_test

  mariadb:
    image: mariadb:10.3
    pull: true
    environment:
      - MYSQL_DATABASE=qb_test
      - MYSQL_USER=qb_test
      - MYSQL_PASSWORD=qb_test
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
