workspace:
  base: /root/go-projects/
  path: src/git.ultraware.nl/NiseVoid/qb

pipeline:
  setup:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    commands:
      - make setup
      - mv /go/src vendor/

  test:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    commands:
      - make test
      - make lint
      - go test -bench=.

  PostgreSQL:
    group: dbtest
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    environment:
      - POSTGRES_TESTHOST=pgsql
    commands:
      - make test_postgres

  MySQL:
    group: dbtest
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    environment:
      - MYSQL_TESTHOST=mariadb
    commands:
      - sleep 5s
      - make test_mysql

  MSSQL:
    group: dbtest
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    environment:
      - MSSQL_TESTHOST=172.22.0.25
    commands:
      - make test_mssql

  total_coverage:
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: true
    commands:
      - cat unit.out > total.out
      - tail -n +2 postgres.out >> total.out
      - tail -n +2 mysql.out >> total.out
      - tail -n +2 mssql.out >> total.out
      - go tool cover -func total.out | tail -1

services:
  pgsql:
    image: postgres:10.1-alpine
    pull: true
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=qb_test
      - POSTGRES_DB=qb_test

  mariadb:
    image: mariadb:10.3
    pull: true
    environment:
      - MYSQL_DATABASE=qb_test
      - MYSQL_USER=qb_test
      - MYSQL_PASSWORD=qb_test
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
